apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  selector:
    app: grpc
  ports:
  - protocol: "TCP"
    port: 6443
    targetPort: 6443
  type: LoadBalancer
  externalIPs:
  - 1.2.4.120

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
spec:
  selector:
    matchLabels:
      app: grpc
  replicas: 4
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: img
        imagePullPolicy: Never
        ports:
        - containerPort: 6443